### ISSUE TITLE
Selected movies showed up on the corner of the webpage

### ISSUE THREAD

**Issue by lingjunliu** [CSC510-GROUP-40/MovieRecommender#17]
**Describe the bug**
Selected movies showed up on the corner of the webpage.

**To Reproduce**
1. Login
2. Select a movie "Toy Story3" and then click "predict"
3. Selected movies showed up on the left corner of the webpage.

**Expected behavior**
There is no duplicated text shown up on the corner

**Screenshots**
![image](https://github.com/user-attachments/assets/a8f13e16-d8d8-4fe6-8c5f-afff97f7dbc0)

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser: google chrome

**Comment by kofiarkoh** [comment]
solved by https://github.com/CSC510-GROUP-40/MovieRecommender/pull/22
