### ISSUE TITLE
Failing Test Case: test_predict_non_json_data()

### ISSUE THREAD

**Issue by lingjunliu** [CSC510-GROUP-40/MovieRecommender#29]
**Describe the bug**
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` occurred when giving non-json data to /predict

**To Reproduce**
1. Use POST method to access "/predict" with a string "Not a JSON"
2. Error occurred

**Expected behavior**
No error

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the /predict route to handle non-JSON input gracefully by adding a try-except block to catch JSONDecodeError. If the input is not valid JSON, it returns a 400 Bad Request response with an error message.

You can review changes in this commit: https://github.com/lkilu6456546/CSC510-GROUP-40-MovieRecommender-29/commit/2fa9c3acf0403c709d77f50a7dc59fc9c3b6992d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
